// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/internal/services (interfaces: DomainServicesGetter,DomainServices)
//
// Generated by this command:
//
//	mockgen -typed -package migrationtarget_test -destination domainservices_mock_test.go github.com/juju/juju/internal/services DomainServicesGetter,DomainServices
//

// Package migrationtarget_test is a generated GoMock package.
package migrationtarget_test

import (
	context "context"
	reflect "reflect"

	model "github.com/juju/juju/core/model"
	service "github.com/juju/juju/domain/access/service"
	service0 "github.com/juju/juju/domain/agentbinary/service"
	service1 "github.com/juju/juju/domain/agentpassword/service"
	service2 "github.com/juju/juju/domain/agentprovisioner/service"
	service3 "github.com/juju/juju/domain/annotation/service"
	service4 "github.com/juju/juju/domain/application/service"
	service5 "github.com/juju/juju/domain/autocert/service"
	service6 "github.com/juju/juju/domain/blockcommand/service"
	service7 "github.com/juju/juju/domain/blockdevice/service"
	service8 "github.com/juju/juju/domain/changestream/service"
	service9 "github.com/juju/juju/domain/cloud/service"
	service10 "github.com/juju/juju/domain/cloudimagemetadata/service"
	service11 "github.com/juju/juju/domain/controller/service"
	service12 "github.com/juju/juju/domain/controllerconfig/service"
	service13 "github.com/juju/juju/domain/controllernode/service"
	service14 "github.com/juju/juju/domain/controllerupgrader/service"
	service15 "github.com/juju/juju/domain/credential/service"
	service16 "github.com/juju/juju/domain/crossmodelrelation/service"
	service17 "github.com/juju/juju/domain/export/service"
	service18 "github.com/juju/juju/domain/externalcontroller/service"
	service19 "github.com/juju/juju/domain/flag/service"
	service20 "github.com/juju/juju/domain/keymanager/service"
	service21 "github.com/juju/juju/domain/keyupdater/service"
	service22 "github.com/juju/juju/domain/macaroon/service"
	service23 "github.com/juju/juju/domain/machine/service"
	service24 "github.com/juju/juju/domain/model/service"
	service25 "github.com/juju/juju/domain/modelagent/service"
	service26 "github.com/juju/juju/domain/modelconfig/service"
	service27 "github.com/juju/juju/domain/modeldefaults/service"
	service28 "github.com/juju/juju/domain/modelmigration/service"
	service29 "github.com/juju/juju/domain/modelprovider/service"
	service30 "github.com/juju/juju/domain/network/service"
	service31 "github.com/juju/juju/domain/operation/service"
	service32 "github.com/juju/juju/domain/port/service"
	service33 "github.com/juju/juju/domain/provisioner/service"
	service34 "github.com/juju/juju/domain/proxy/service"
	service35 "github.com/juju/juju/domain/relation/service"
	service36 "github.com/juju/juju/domain/removal/service"
	service37 "github.com/juju/juju/domain/resolve/service"
	service38 "github.com/juju/juju/domain/resource/service"
	service39 "github.com/juju/juju/domain/secret/service"
	service40 "github.com/juju/juju/domain/secretbackend/service"
	service41 "github.com/juju/juju/domain/status/service"
	service42 "github.com/juju/juju/domain/storage/service"
	service43 "github.com/juju/juju/domain/storageprovisioning/service"
	service44 "github.com/juju/juju/domain/tracing/service"
	service45 "github.com/juju/juju/domain/unitstate/service"
	service46 "github.com/juju/juju/domain/upgrade/service"
	services "github.com/juju/juju/internal/services"
	gomock "go.uber.org/mock/gomock"
)
import (
	context "context"
	reflect "reflect"

	model "github.com/juju/juju/core/model"
	service "github.com/juju/juju/domain/access/service"
	service0 "github.com/juju/juju/domain/agentbinary/service"
	service1 "github.com/juju/juju/domain/agentpassword/service"
	service2 "github.com/juju/juju/domain/agentprovisioner/service"
	service3 "github.com/juju/juju/domain/annotation/service"
	service4 "github.com/juju/juju/domain/application/service"
	service5 "github.com/juju/juju/domain/autocert/service"
	service6 "github.com/juju/juju/domain/blockcommand/service"
	service7 "github.com/juju/juju/domain/blockdevice/service"
	service8 "github.com/juju/juju/domain/changestream/service"
	service9 "github.com/juju/juju/domain/cloud/service"
	service10 "github.com/juju/juju/domain/cloudimagemetadata/service"
	service11 "github.com/juju/juju/domain/controller/service"
	service12 "github.com/juju/juju/domain/controllerconfig/service"
	service13 "github.com/juju/juju/domain/controllernode/service"
	service14 "github.com/juju/juju/domain/controllerupgrader/service"
	service15 "github.com/juju/juju/domain/credential/service"
	service16 "github.com/juju/juju/domain/crossmodelrelation/service"
	service17 "github.com/juju/juju/domain/export/service"
	service18 "github.com/juju/juju/domain/externalcontroller/service"
	service19 "github.com/juju/juju/domain/flag/service"
	service20 "github.com/juju/juju/domain/keymanager/service"
	service21 "github.com/juju/juju/domain/keyupdater/service"
	service22 "github.com/juju/juju/domain/logging/service"
	service23 "github.com/juju/juju/domain/macaroon/service"
	service24 "github.com/juju/juju/domain/machine/service"
	service25 "github.com/juju/juju/domain/model/service"
	service26 "github.com/juju/juju/domain/modelagent/service"
	service27 "github.com/juju/juju/domain/modelconfig/service"
	service28 "github.com/juju/juju/domain/modeldefaults/service"
	service29 "github.com/juju/juju/domain/modelmigration/service"
	service30 "github.com/juju/juju/domain/modelprovider/service"
	service31 "github.com/juju/juju/domain/network/service"
	service32 "github.com/juju/juju/domain/operation/service"
	service33 "github.com/juju/juju/domain/port/service"
	service34 "github.com/juju/juju/domain/proxy/service"
	service35 "github.com/juju/juju/domain/relation/service"
	service36 "github.com/juju/juju/domain/removal/service"
	service37 "github.com/juju/juju/domain/resolve/service"
	service38 "github.com/juju/juju/domain/resource/service"
	service39 "github.com/juju/juju/domain/secret/service"
	service40 "github.com/juju/juju/domain/secretbackend/service"
	service41 "github.com/juju/juju/domain/status/service"
	service42 "github.com/juju/juju/domain/storage/service"
	service43 "github.com/juju/juju/domain/storageprovisioning/service"
	service44 "github.com/juju/juju/domain/tracing/service"
	service45 "github.com/juju/juju/domain/unitstate/service"
	service46 "github.com/juju/juju/domain/upgrade/service"
	services "github.com/juju/juju/internal/services"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainServicesGetter is a mock of DomainServicesGetter interface.
type MockDomainServicesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockDomainServicesGetterMockRecorder
}

// MockDomainServicesGetterMockRecorder is the mock recorder for MockDomainServicesGetter.
type MockDomainServicesGetterMockRecorder struct {
	mock *MockDomainServicesGetter
}

// NewMockDomainServicesGetter creates a new mock instance.
func NewMockDomainServicesGetter(ctrl *gomock.Controller) *MockDomainServicesGetter {
	mock := &MockDomainServicesGetter{ctrl: ctrl}
	mock.recorder = &MockDomainServicesGetterMockRecorder{mock}
	return mock
}
func NewMockDomainServices(ctrl *gomock.Controller) *MockDomainServices {
	mock := &MockDomainServices{ctrl: ctrl}
	mock.recorder = &MockDomainServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainServicesGetter) EXPECT() *MockDomainServicesGetterMockRecorder {
	return m.recorder
}
func (m *MockDomainServicesGetter) ServicesForModel(arg0 context.Context, arg1 model.UUID) (services.DomainServices, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServicesForModel", arg0, arg1)
	ret0, _ := ret[0].(services.DomainServices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockDomainServicesGetterMockRecorder) ServicesForModel(arg0, arg1 any) *MockDomainServicesGetterServicesForModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServicesForModel", reflect.TypeOf((*MockDomainServicesGetter)(nil).ServicesForModel), arg0, arg1)
	return &MockDomainServicesGetterServicesForModelCall{Call: call}
}
func (c *MockDomainServicesGetterServicesForModelCall) Return(arg0 services.DomainServices, arg1 error) *MockDomainServicesGetterServicesForModelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}
func (c *MockDomainServicesGetterServicesForModelCall) Do(f func(context.Context, model.UUID) (services.DomainServices, error)) *MockDomainServicesGetterServicesForModelCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesGetterServicesForModelCall) DoAndReturn(f func(context.Context, model.UUID) (services.DomainServices, error)) *MockDomainServicesGetterServicesForModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) EXPECT() *MockDomainServicesMockRecorder {
	return m.recorder
}
func (m *MockDomainServices) Access() *service.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Access")
	ret0, _ := ret[0].(*service.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Access() *MockDomainServicesAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Access", reflect.TypeOf((*MockDomainServices)(nil).Access))
	return &MockDomainServicesAccessCall{Call: call}
}
func (c *MockDomainServicesAccessCall) Return(arg0 *service.Service) *MockDomainServicesAccessCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAccessCall) Do(f func() *service.Service) *MockDomainServicesAccessCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAccessCall) DoAndReturn(f func() *service.Service) *MockDomainServicesAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Agent() *service26.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Agent")
	ret0, _ := ret[0].(*service26.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Agent() *MockDomainServicesAgentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Agent", reflect.TypeOf((*MockDomainServices)(nil).Agent))
	return &MockDomainServicesAgentCall{Call: call}
}
func (c *MockDomainServicesAgentCall) Return(arg0 *service26.WatchableService) *MockDomainServicesAgentCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAgentCall) Do(f func() *service26.WatchableService) *MockDomainServicesAgentCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAgentCall) DoAndReturn(f func() *service26.WatchableService) *MockDomainServicesAgentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) AgentBinary() *service0.AgentBinaryService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentBinary")
	ret0, _ := ret[0].(*service0.AgentBinaryService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) AgentBinary() *MockDomainServicesAgentBinaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentBinary", reflect.TypeOf((*MockDomainServices)(nil).AgentBinary))
	return &MockDomainServicesAgentBinaryCall{Call: call}
}
func (c *MockDomainServicesAgentBinaryCall) Return(arg0 *service0.AgentBinaryService) *MockDomainServicesAgentBinaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAgentBinaryCall) Do(f func() *service0.AgentBinaryService) *MockDomainServicesAgentBinaryCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAgentBinaryCall) DoAndReturn(f func() *service0.AgentBinaryService) *MockDomainServicesAgentBinaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) AgentBinaryStore() *service0.AgentBinaryStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentBinaryStore")
	ret0, _ := ret[0].(*service0.AgentBinaryStore)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) AgentBinaryStore() *MockDomainServicesAgentBinaryStoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentBinaryStore", reflect.TypeOf((*MockDomainServices)(nil).AgentBinaryStore))
	return &MockDomainServicesAgentBinaryStoreCall{Call: call}
}
func (c *MockDomainServicesAgentBinaryStoreCall) Return(arg0 *service0.AgentBinaryStore) *MockDomainServicesAgentBinaryStoreCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAgentBinaryStoreCall) Do(f func() *service0.AgentBinaryStore) *MockDomainServicesAgentBinaryStoreCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAgentBinaryStoreCall) DoAndReturn(f func() *service0.AgentBinaryStore) *MockDomainServicesAgentBinaryStoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) AgentPassword() *service1.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentPassword")
	ret0, _ := ret[0].(*service1.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) AgentPassword() *MockDomainServicesAgentPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentPassword", reflect.TypeOf((*MockDomainServices)(nil).AgentPassword))
	return &MockDomainServicesAgentPasswordCall{Call: call}
}
func (c *MockDomainServicesAgentPasswordCall) Return(arg0 *service1.Service) *MockDomainServicesAgentPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAgentPasswordCall) Do(f func() *service1.Service) *MockDomainServicesAgentPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAgentPasswordCall) DoAndReturn(f func() *service1.Service) *MockDomainServicesAgentPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) AgentProvisioner() *service2.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentProvisioner")
	ret0, _ := ret[0].(*service2.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) AgentProvisioner() *MockDomainServicesAgentProvisionerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentProvisioner", reflect.TypeOf((*MockDomainServices)(nil).AgentProvisioner))
	return &MockDomainServicesAgentProvisionerCall{Call: call}
}
func (c *MockDomainServicesAgentProvisionerCall) Return(arg0 *service2.Service) *MockDomainServicesAgentProvisionerCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAgentProvisionerCall) Do(f func() *service2.Service) *MockDomainServicesAgentProvisionerCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAgentProvisionerCall) DoAndReturn(f func() *service2.Service) *MockDomainServicesAgentProvisionerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Annotation() *service3.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Annotation")
	ret0, _ := ret[0].(*service3.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Annotation() *MockDomainServicesAnnotationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Annotation", reflect.TypeOf((*MockDomainServices)(nil).Annotation))
	return &MockDomainServicesAnnotationCall{Call: call}
}
func (c *MockDomainServicesAnnotationCall) Return(arg0 *service3.Service) *MockDomainServicesAnnotationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAnnotationCall) Do(f func() *service3.Service) *MockDomainServicesAnnotationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAnnotationCall) DoAndReturn(f func() *service3.Service) *MockDomainServicesAnnotationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Application() *service4.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Application")
	ret0, _ := ret[0].(*service4.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Application() *MockDomainServicesApplicationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Application", reflect.TypeOf((*MockDomainServices)(nil).Application))
	return &MockDomainServicesApplicationCall{Call: call}
}
func (c *MockDomainServicesApplicationCall) Return(arg0 *service4.WatchableService) *MockDomainServicesApplicationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesApplicationCall) Do(f func() *service4.WatchableService) *MockDomainServicesApplicationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesApplicationCall) DoAndReturn(f func() *service4.WatchableService) *MockDomainServicesApplicationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) AutocertCache() *service5.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutocertCache")
	ret0, _ := ret[0].(*service5.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) AutocertCache() *MockDomainServicesAutocertCacheCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutocertCache", reflect.TypeOf((*MockDomainServices)(nil).AutocertCache))
	return &MockDomainServicesAutocertCacheCall{Call: call}
}
func (c *MockDomainServicesAutocertCacheCall) Return(arg0 *service5.Service) *MockDomainServicesAutocertCacheCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesAutocertCacheCall) Do(f func() *service5.Service) *MockDomainServicesAutocertCacheCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesAutocertCacheCall) DoAndReturn(f func() *service5.Service) *MockDomainServicesAutocertCacheCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) BlockCommand() *service6.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockCommand")
	ret0, _ := ret[0].(*service6.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) BlockCommand() *MockDomainServicesBlockCommandCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockCommand", reflect.TypeOf((*MockDomainServices)(nil).BlockCommand))
	return &MockDomainServicesBlockCommandCall{Call: call}
}
func (c *MockDomainServicesBlockCommandCall) Return(arg0 *service6.Service) *MockDomainServicesBlockCommandCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesBlockCommandCall) Do(f func() *service6.Service) *MockDomainServicesBlockCommandCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesBlockCommandCall) DoAndReturn(f func() *service6.Service) *MockDomainServicesBlockCommandCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) BlockDevice() *service7.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockDevice")
	ret0, _ := ret[0].(*service7.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) BlockDevice() *MockDomainServicesBlockDeviceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockDevice", reflect.TypeOf((*MockDomainServices)(nil).BlockDevice))
	return &MockDomainServicesBlockDeviceCall{Call: call}
}
func (c *MockDomainServicesBlockDeviceCall) Return(arg0 *service7.WatchableService) *MockDomainServicesBlockDeviceCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesBlockDeviceCall) Do(f func() *service7.WatchableService) *MockDomainServicesBlockDeviceCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesBlockDeviceCall) DoAndReturn(f func() *service7.WatchableService) *MockDomainServicesBlockDeviceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ChangeStream() *service8.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStream")
	ret0, _ := ret[0].(*service8.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ChangeStream() *MockDomainServicesChangeStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStream", reflect.TypeOf((*MockDomainServices)(nil).ChangeStream))
	return &MockDomainServicesChangeStreamCall{Call: call}
}
func (c *MockDomainServicesChangeStreamCall) Return(arg0 *service8.Service) *MockDomainServicesChangeStreamCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesChangeStreamCall) Do(f func() *service8.Service) *MockDomainServicesChangeStreamCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesChangeStreamCall) DoAndReturn(f func() *service8.Service) *MockDomainServicesChangeStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Cloud() *service9.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cloud")
	ret0, _ := ret[0].(*service9.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Cloud() *MockDomainServicesCloudCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cloud", reflect.TypeOf((*MockDomainServices)(nil).Cloud))
	return &MockDomainServicesCloudCall{Call: call}
}
func (c *MockDomainServicesCloudCall) Return(arg0 *service9.WatchableService) *MockDomainServicesCloudCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesCloudCall) Do(f func() *service9.WatchableService) *MockDomainServicesCloudCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesCloudCall) DoAndReturn(f func() *service9.WatchableService) *MockDomainServicesCloudCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) CloudImageMetadata() *service10.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudImageMetadata")
	ret0, _ := ret[0].(*service10.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) CloudImageMetadata() *MockDomainServicesCloudImageMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudImageMetadata", reflect.TypeOf((*MockDomainServices)(nil).CloudImageMetadata))
	return &MockDomainServicesCloudImageMetadataCall{Call: call}
}
func (c *MockDomainServicesCloudImageMetadataCall) Return(arg0 *service10.Service) *MockDomainServicesCloudImageMetadataCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesCloudImageMetadataCall) Do(f func() *service10.Service) *MockDomainServicesCloudImageMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesCloudImageMetadataCall) DoAndReturn(f func() *service10.Service) *MockDomainServicesCloudImageMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Config() *service27.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*service27.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Config() *MockDomainServicesConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockDomainServices)(nil).Config))
	return &MockDomainServicesConfigCall{Call: call}
}
func (c *MockDomainServicesConfigCall) Return(arg0 *service27.WatchableService) *MockDomainServicesConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesConfigCall) Do(f func() *service27.WatchableService) *MockDomainServicesConfigCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesConfigCall) DoAndReturn(f func() *service27.WatchableService) *MockDomainServicesConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Controller() *service11.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Controller")
	ret0, _ := ret[0].(*service11.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Controller() *MockDomainServicesControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controller", reflect.TypeOf((*MockDomainServices)(nil).Controller))
	return &MockDomainServicesControllerCall{Call: call}
}
func (c *MockDomainServicesControllerCall) Return(arg0 *service11.Service) *MockDomainServicesControllerCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerCall) Do(f func() *service11.Service) *MockDomainServicesControllerCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerCall) DoAndReturn(f func() *service11.Service) *MockDomainServicesControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ControllerAgentBinaryStore() *service0.AgentBinaryStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerAgentBinaryStore")
	ret0, _ := ret[0].(*service0.AgentBinaryStore)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ControllerAgentBinaryStore() *MockDomainServicesControllerAgentBinaryStoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerAgentBinaryStore", reflect.TypeOf((*MockDomainServices)(nil).ControllerAgentBinaryStore))
	return &MockDomainServicesControllerAgentBinaryStoreCall{Call: call}
}
func (c *MockDomainServicesControllerAgentBinaryStoreCall) Return(arg0 *service0.AgentBinaryStore) *MockDomainServicesControllerAgentBinaryStoreCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerAgentBinaryStoreCall) Do(f func() *service0.AgentBinaryStore) *MockDomainServicesControllerAgentBinaryStoreCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerAgentBinaryStoreCall) DoAndReturn(f func() *service0.AgentBinaryStore) *MockDomainServicesControllerAgentBinaryStoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ControllerChangeStream() *service8.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerChangeStream")
	ret0, _ := ret[0].(*service8.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ControllerChangeStream() *MockDomainServicesControllerChangeStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerChangeStream", reflect.TypeOf((*MockDomainServices)(nil).ControllerChangeStream))
	return &MockDomainServicesControllerChangeStreamCall{Call: call}
}
func (c *MockDomainServicesControllerChangeStreamCall) Return(arg0 *service8.Service) *MockDomainServicesControllerChangeStreamCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerChangeStreamCall) Do(f func() *service8.Service) *MockDomainServicesControllerChangeStreamCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerChangeStreamCall) DoAndReturn(f func() *service8.Service) *MockDomainServicesControllerChangeStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ControllerConfig() *service12.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerConfig")
	ret0, _ := ret[0].(*service12.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ControllerConfig() *MockDomainServicesControllerConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerConfig", reflect.TypeOf((*MockDomainServices)(nil).ControllerConfig))
	return &MockDomainServicesControllerConfigCall{Call: call}
}
func (c *MockDomainServicesControllerConfigCall) Return(arg0 *service12.WatchableService) *MockDomainServicesControllerConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerConfigCall) Do(f func() *service12.WatchableService) *MockDomainServicesControllerConfigCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerConfigCall) DoAndReturn(f func() *service12.WatchableService) *MockDomainServicesControllerConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ControllerNode() *service13.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerNode")
	ret0, _ := ret[0].(*service13.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ControllerNode() *MockDomainServicesControllerNodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerNode", reflect.TypeOf((*MockDomainServices)(nil).ControllerNode))
	return &MockDomainServicesControllerNodeCall{Call: call}
}
func (c *MockDomainServicesControllerNodeCall) Return(arg0 *service13.WatchableService) *MockDomainServicesControllerNodeCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerNodeCall) Do(f func() *service13.WatchableService) *MockDomainServicesControllerNodeCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerNodeCall) DoAndReturn(f func() *service13.WatchableService) *MockDomainServicesControllerNodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ControllerUpgrader() *service14.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerUpgrader")
	ret0, _ := ret[0].(*service14.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ControllerUpgrader() *MockDomainServicesControllerUpgraderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerUpgrader", reflect.TypeOf((*MockDomainServices)(nil).ControllerUpgrader))
	return &MockDomainServicesControllerUpgraderCall{Call: call}
}
func (c *MockDomainServicesControllerUpgraderCall) Return(arg0 *service14.Service) *MockDomainServicesControllerUpgraderCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesControllerUpgraderCall) Do(f func() *service14.Service) *MockDomainServicesControllerUpgraderCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesControllerUpgraderCall) DoAndReturn(f func() *service14.Service) *MockDomainServicesControllerUpgraderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Credential() *service15.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credential")
	ret0, _ := ret[0].(*service15.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Credential() *MockDomainServicesCredentialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credential", reflect.TypeOf((*MockDomainServices)(nil).Credential))
	return &MockDomainServicesCredentialCall{Call: call}
}
func (c *MockDomainServicesCredentialCall) Return(arg0 *service15.WatchableService) *MockDomainServicesCredentialCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesCredentialCall) Do(f func() *service15.WatchableService) *MockDomainServicesCredentialCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesCredentialCall) DoAndReturn(f func() *service15.WatchableService) *MockDomainServicesCredentialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) CrossModelRelation() *service16.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CrossModelRelation")
	ret0, _ := ret[0].(*service16.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) CrossModelRelation() *MockDomainServicesCrossModelRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CrossModelRelation", reflect.TypeOf((*MockDomainServices)(nil).CrossModelRelation))
	return &MockDomainServicesCrossModelRelationCall{Call: call}
}
func (c *MockDomainServicesCrossModelRelationCall) Return(arg0 *service16.WatchableService) *MockDomainServicesCrossModelRelationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesCrossModelRelationCall) Do(f func() *service16.WatchableService) *MockDomainServicesCrossModelRelationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesCrossModelRelationCall) DoAndReturn(f func() *service16.WatchableService) *MockDomainServicesCrossModelRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Export() *service17.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export")
	ret0, _ := ret[0].(*service17.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Export() *MockDomainServicesExportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockDomainServices)(nil).Export))
	return &MockDomainServicesExportCall{Call: call}
}
func (c *MockDomainServicesExportCall) Return(arg0 *service17.Service) *MockDomainServicesExportCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesExportCall) Do(f func() *service17.Service) *MockDomainServicesExportCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesExportCall) DoAndReturn(f func() *service17.Service) *MockDomainServicesExportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ExternalController() *service18.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExternalController")
	ret0, _ := ret[0].(*service18.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ExternalController() *MockDomainServicesExternalControllerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExternalController", reflect.TypeOf((*MockDomainServices)(nil).ExternalController))
	return &MockDomainServicesExternalControllerCall{Call: call}
}
func (c *MockDomainServicesExternalControllerCall) Return(arg0 *service18.WatchableService) *MockDomainServicesExternalControllerCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesExternalControllerCall) Do(f func() *service18.WatchableService) *MockDomainServicesExternalControllerCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesExternalControllerCall) DoAndReturn(f func() *service18.WatchableService) *MockDomainServicesExternalControllerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Flag() *service19.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flag")
	ret0, _ := ret[0].(*service19.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Flag() *MockDomainServicesFlagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flag", reflect.TypeOf((*MockDomainServices)(nil).Flag))
	return &MockDomainServicesFlagCall{Call: call}
}
func (c *MockDomainServicesFlagCall) Return(arg0 *service19.Service) *MockDomainServicesFlagCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesFlagCall) Do(f func() *service19.Service) *MockDomainServicesFlagCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesFlagCall) DoAndReturn(f func() *service19.Service) *MockDomainServicesFlagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) KeyManager() *service20.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyManager")
	ret0, _ := ret[0].(*service20.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) KeyManager() *MockDomainServicesKeyManagerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyManager", reflect.TypeOf((*MockDomainServices)(nil).KeyManager))
	return &MockDomainServicesKeyManagerCall{Call: call}
}
func (c *MockDomainServicesKeyManagerCall) Return(arg0 *service20.Service) *MockDomainServicesKeyManagerCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesKeyManagerCall) Do(f func() *service20.Service) *MockDomainServicesKeyManagerCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesKeyManagerCall) DoAndReturn(f func() *service20.Service) *MockDomainServicesKeyManagerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) KeyManagerWithImporter() *service20.ImporterService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyManagerWithImporter")
	ret0, _ := ret[0].(*service20.ImporterService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) KeyManagerWithImporter() *MockDomainServicesKeyManagerWithImporterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyManagerWithImporter", reflect.TypeOf((*MockDomainServices)(nil).KeyManagerWithImporter))
	return &MockDomainServicesKeyManagerWithImporterCall{Call: call}
}
func (c *MockDomainServicesKeyManagerWithImporterCall) Return(arg0 *service20.ImporterService) *MockDomainServicesKeyManagerWithImporterCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesKeyManagerWithImporterCall) Do(f func() *service20.ImporterService) *MockDomainServicesKeyManagerWithImporterCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesKeyManagerWithImporterCall) DoAndReturn(f func() *service20.ImporterService) *MockDomainServicesKeyManagerWithImporterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) KeyUpdater() *service21.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyUpdater")
	ret0, _ := ret[0].(*service21.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) KeyUpdater() *MockDomainServicesKeyUpdaterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyUpdater", reflect.TypeOf((*MockDomainServices)(nil).KeyUpdater))
	return &MockDomainServicesKeyUpdaterCall{Call: call}
}
func (c *MockDomainServicesKeyUpdaterCall) Return(arg0 *service21.WatchableService) *MockDomainServicesKeyUpdaterCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesKeyUpdaterCall) Do(f func() *service21.WatchableService) *MockDomainServicesKeyUpdaterCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesKeyUpdaterCall) DoAndReturn(f func() *service21.WatchableService) *MockDomainServicesKeyUpdaterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Logging() *service22.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logging")
	ret0, _ := ret[0].(*service22.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Logging() *MockDomainServicesLoggingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logging", reflect.TypeOf((*MockDomainServices)(nil).Logging))
	return &MockDomainServicesLoggingCall{Call: call}
}
func (c *MockDomainServicesLoggingCall) Return(arg0 *service22.WatchableService) *MockDomainServicesLoggingCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesLoggingCall) Do(f func() *service22.WatchableService) *MockDomainServicesLoggingCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesLoggingCall) DoAndReturn(f func() *service22.WatchableService) *MockDomainServicesLoggingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Macaroon() *service23.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Macaroon")
	ret0, _ := ret[0].(*service23.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Macaroon() *MockDomainServicesMacaroonCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Macaroon", reflect.TypeOf((*MockDomainServices)(nil).Macaroon))
	return &MockDomainServicesMacaroonCall{Call: call}
}
func (c *MockDomainServicesMacaroonCall) Return(arg0 *service23.Service) *MockDomainServicesMacaroonCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesMacaroonCall) Do(f func() *service23.Service) *MockDomainServicesMacaroonCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesMacaroonCall) DoAndReturn(f func() *service23.Service) *MockDomainServicesMacaroonCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Machine() *service24.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Machine")
	ret0, _ := ret[0].(*service24.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Machine() *MockDomainServicesMachineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Machine", reflect.TypeOf((*MockDomainServices)(nil).Machine))
	return &MockDomainServicesMachineCall{Call: call}
}
func (c *MockDomainServicesMachineCall) Return(arg0 *service24.WatchableService) *MockDomainServicesMachineCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesMachineCall) Do(f func() *service24.WatchableService) *MockDomainServicesMachineCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesMachineCall) DoAndReturn(f func() *service24.WatchableService) *MockDomainServicesMachineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Model() *service25.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model")
	ret0, _ := ret[0].(*service25.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Model() *MockDomainServicesModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockDomainServices)(nil).Model))
	return &MockDomainServicesModelCall{Call: call}
}
func (c *MockDomainServicesModelCall) Return(arg0 *service25.WatchableService) *MockDomainServicesModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelCall) Do(f func() *service25.WatchableService) *MockDomainServicesModelCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelCall) DoAndReturn(f func() *service25.WatchableService) *MockDomainServicesModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ModelDefaults() *service28.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelDefaults")
	ret0, _ := ret[0].(*service28.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ModelDefaults() *MockDomainServicesModelDefaultsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelDefaults", reflect.TypeOf((*MockDomainServices)(nil).ModelDefaults))
	return &MockDomainServicesModelDefaultsCall{Call: call}
}
func (c *MockDomainServicesModelDefaultsCall) Return(arg0 *service28.Service) *MockDomainServicesModelDefaultsCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelDefaultsCall) Do(f func() *service28.Service) *MockDomainServicesModelDefaultsCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelDefaultsCall) DoAndReturn(f func() *service28.Service) *MockDomainServicesModelDefaultsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ModelInfo() *service25.ProviderModelService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelInfo")
	ret0, _ := ret[0].(*service25.ProviderModelService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ModelInfo() *MockDomainServicesModelInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelInfo", reflect.TypeOf((*MockDomainServices)(nil).ModelInfo))
	return &MockDomainServicesModelInfoCall{Call: call}
}
func (c *MockDomainServicesModelInfoCall) Return(arg0 *service25.ProviderModelService) *MockDomainServicesModelInfoCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelInfoCall) Do(f func() *service25.ProviderModelService) *MockDomainServicesModelInfoCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelInfoCall) DoAndReturn(f func() *service25.ProviderModelService) *MockDomainServicesModelInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ModelMigration() *service29.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelMigration")
	ret0, _ := ret[0].(*service29.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ModelMigration() *MockDomainServicesModelMigrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelMigration", reflect.TypeOf((*MockDomainServices)(nil).ModelMigration))
	return &MockDomainServicesModelMigrationCall{Call: call}
}
func (c *MockDomainServicesModelMigrationCall) Return(arg0 *service29.Service) *MockDomainServicesModelMigrationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelMigrationCall) Do(f func() *service29.Service) *MockDomainServicesModelMigrationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelMigrationCall) DoAndReturn(f func() *service29.Service) *MockDomainServicesModelMigrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ModelProvider() *service30.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelProvider")
	ret0, _ := ret[0].(*service30.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ModelProvider() *MockDomainServicesModelProviderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelProvider", reflect.TypeOf((*MockDomainServices)(nil).ModelProvider))
	return &MockDomainServicesModelProviderCall{Call: call}
}
func (c *MockDomainServicesModelProviderCall) Return(arg0 *service30.Service) *MockDomainServicesModelProviderCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelProviderCall) Do(f func() *service30.Service) *MockDomainServicesModelProviderCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelProviderCall) DoAndReturn(f func() *service30.Service) *MockDomainServicesModelProviderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) ModelSecretBackend() *service40.ModelSecretBackendService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelSecretBackend")
	ret0, _ := ret[0].(*service40.ModelSecretBackendService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) ModelSecretBackend() *MockDomainServicesModelSecretBackendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelSecretBackend", reflect.TypeOf((*MockDomainServices)(nil).ModelSecretBackend))
	return &MockDomainServicesModelSecretBackendCall{Call: call}
}
func (c *MockDomainServicesModelSecretBackendCall) Return(arg0 *service40.ModelSecretBackendService) *MockDomainServicesModelSecretBackendCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesModelSecretBackendCall) Do(f func() *service40.ModelSecretBackendService) *MockDomainServicesModelSecretBackendCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesModelSecretBackendCall) DoAndReturn(f func() *service40.ModelSecretBackendService) *MockDomainServicesModelSecretBackendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Network() *service31.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Network")
	ret0, _ := ret[0].(*service31.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Network() *MockDomainServicesNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Network", reflect.TypeOf((*MockDomainServices)(nil).Network))
	return &MockDomainServicesNetworkCall{Call: call}
}
func (c *MockDomainServicesNetworkCall) Return(arg0 *service31.WatchableService) *MockDomainServicesNetworkCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesNetworkCall) Do(f func() *service31.WatchableService) *MockDomainServicesNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesNetworkCall) DoAndReturn(f func() *service31.WatchableService) *MockDomainServicesNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Operation() *service32.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operation")
	ret0, _ := ret[0].(*service32.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Operation() *MockDomainServicesOperationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operation", reflect.TypeOf((*MockDomainServices)(nil).Operation))
	return &MockDomainServicesOperationCall{Call: call}
}
func (c *MockDomainServicesOperationCall) Return(arg0 *service32.WatchableService) *MockDomainServicesOperationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesOperationCall) Do(f func() *service32.WatchableService) *MockDomainServicesOperationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesOperationCall) DoAndReturn(f func() *service32.WatchableService) *MockDomainServicesOperationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Port() *service33.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Port")
	ret0, _ := ret[0].(*service33.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Port() *MockDomainServicesPortCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Port", reflect.TypeOf((*MockDomainServices)(nil).Port))
	return &MockDomainServicesPortCall{Call: call}
}
func (c *MockDomainServicesPortCall) Return(arg0 *service33.WatchableService) *MockDomainServicesPortCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesPortCall) Do(f func() *service33.WatchableService) *MockDomainServicesPortCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesPortCall) DoAndReturn(f func() *service33.WatchableService) *MockDomainServicesPortCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Provisioning() *service33.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provisioning")
	ret0, _ := ret[0].(*service33.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Provisioning() *MockDomainServicesProvisioningCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provisioning", reflect.TypeOf((*MockDomainServices)(nil).Provisioning))
	return &MockDomainServicesProvisioningCall{Call: call}
}
func (c *MockDomainServicesProvisioningCall) Return(arg0 *service33.Service) *MockDomainServicesProvisioningCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesProvisioningCall) Do(f func() *service33.Service) *MockDomainServicesProvisioningCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesProvisioningCall) DoAndReturn(f func() *service33.Service) *MockDomainServicesProvisioningCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Proxy() *service34.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proxy")
	ret0, _ := ret[0].(*service34.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Proxy() *MockDomainServicesProxyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proxy", reflect.TypeOf((*MockDomainServices)(nil).Proxy))
	return &MockDomainServicesProxyCall{Call: call}
}
func (c *MockDomainServicesProxyCall) Return(arg0 *service34.Service) *MockDomainServicesProxyCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesProxyCall) Do(f func() *service34.Service) *MockDomainServicesProxyCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesProxyCall) DoAndReturn(f func() *service34.Service) *MockDomainServicesProxyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Relation() *service35.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relation")
	ret0, _ := ret[0].(*service35.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Relation() *MockDomainServicesRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relation", reflect.TypeOf((*MockDomainServices)(nil).Relation))
	return &MockDomainServicesRelationCall{Call: call}
}
func (c *MockDomainServicesRelationCall) Return(arg0 *service35.WatchableService) *MockDomainServicesRelationCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesRelationCall) Do(f func() *service35.WatchableService) *MockDomainServicesRelationCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesRelationCall) DoAndReturn(f func() *service35.WatchableService) *MockDomainServicesRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Removal() *service36.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Removal")
	ret0, _ := ret[0].(*service36.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Removal() *MockDomainServicesRemovalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Removal", reflect.TypeOf((*MockDomainServices)(nil).Removal))
	return &MockDomainServicesRemovalCall{Call: call}
}
func (c *MockDomainServicesRemovalCall) Return(arg0 *service36.WatchableService) *MockDomainServicesRemovalCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesRemovalCall) Do(f func() *service36.WatchableService) *MockDomainServicesRemovalCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesRemovalCall) DoAndReturn(f func() *service36.WatchableService) *MockDomainServicesRemovalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Resolve() *service37.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve")
	ret0, _ := ret[0].(*service37.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Resolve() *MockDomainServicesResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockDomainServices)(nil).Resolve))
	return &MockDomainServicesResolveCall{Call: call}
}
func (c *MockDomainServicesResolveCall) Return(arg0 *service37.WatchableService) *MockDomainServicesResolveCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesResolveCall) Do(f func() *service37.WatchableService) *MockDomainServicesResolveCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesResolveCall) DoAndReturn(f func() *service37.WatchableService) *MockDomainServicesResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Resource() *service38.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resource")
	ret0, _ := ret[0].(*service38.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Resource() *MockDomainServicesResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resource", reflect.TypeOf((*MockDomainServices)(nil).Resource))
	return &MockDomainServicesResourceCall{Call: call}
}
func (c *MockDomainServicesResourceCall) Return(arg0 *service38.Service) *MockDomainServicesResourceCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesResourceCall) Do(f func() *service38.Service) *MockDomainServicesResourceCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesResourceCall) DoAndReturn(f func() *service38.Service) *MockDomainServicesResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Secret() *service39.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secret")
	ret0, _ := ret[0].(*service39.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Secret() *MockDomainServicesSecretCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secret", reflect.TypeOf((*MockDomainServices)(nil).Secret))
	return &MockDomainServicesSecretCall{Call: call}
}
func (c *MockDomainServicesSecretCall) Return(arg0 *service39.WatchableService) *MockDomainServicesSecretCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesSecretCall) Do(f func() *service39.WatchableService) *MockDomainServicesSecretCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesSecretCall) DoAndReturn(f func() *service39.WatchableService) *MockDomainServicesSecretCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) SecretBackend() *service40.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretBackend")
	ret0, _ := ret[0].(*service40.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) SecretBackend() *MockDomainServicesSecretBackendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretBackend", reflect.TypeOf((*MockDomainServices)(nil).SecretBackend))
	return &MockDomainServicesSecretBackendCall{Call: call}
}
func (c *MockDomainServicesSecretBackendCall) Return(arg0 *service40.WatchableService) *MockDomainServicesSecretBackendCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesSecretBackendCall) Do(f func() *service40.WatchableService) *MockDomainServicesSecretBackendCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesSecretBackendCall) DoAndReturn(f func() *service40.WatchableService) *MockDomainServicesSecretBackendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Status() *service41.LeadershipService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(*service41.LeadershipService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Status() *MockDomainServicesStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockDomainServices)(nil).Status))
	return &MockDomainServicesStatusCall{Call: call}
}
func (c *MockDomainServicesStatusCall) Return(arg0 *service41.LeadershipService) *MockDomainServicesStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesStatusCall) Do(f func() *service41.LeadershipService) *MockDomainServicesStatusCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesStatusCall) DoAndReturn(f func() *service41.LeadershipService) *MockDomainServicesStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Storage() *service42.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage")
	ret0, _ := ret[0].(*service42.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Storage() *MockDomainServicesStorageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockDomainServices)(nil).Storage))
	return &MockDomainServicesStorageCall{Call: call}
}
func (c *MockDomainServicesStorageCall) Return(arg0 *service42.Service) *MockDomainServicesStorageCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesStorageCall) Do(f func() *service42.Service) *MockDomainServicesStorageCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesStorageCall) DoAndReturn(f func() *service42.Service) *MockDomainServicesStorageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) StorageProvisioning() *service43.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageProvisioning")
	ret0, _ := ret[0].(*service43.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) StorageProvisioning() *MockDomainServicesStorageProvisioningCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageProvisioning", reflect.TypeOf((*MockDomainServices)(nil).StorageProvisioning))
	return &MockDomainServicesStorageProvisioningCall{Call: call}
}
func (c *MockDomainServicesStorageProvisioningCall) Return(arg0 *service43.Service) *MockDomainServicesStorageProvisioningCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesStorageProvisioningCall) Do(f func() *service43.Service) *MockDomainServicesStorageProvisioningCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesStorageProvisioningCall) DoAndReturn(f func() *service43.Service) *MockDomainServicesStorageProvisioningCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Tracing() *service44.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tracing")
	ret0, _ := ret[0].(*service44.Service)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Tracing() *MockDomainServicesTracingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tracing", reflect.TypeOf((*MockDomainServices)(nil).Tracing))
	return &MockDomainServicesTracingCall{Call: call}
}
func (c *MockDomainServicesTracingCall) Return(arg0 *service44.Service) *MockDomainServicesTracingCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesTracingCall) Do(f func() *service44.Service) *MockDomainServicesTracingCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesTracingCall) DoAndReturn(f func() *service44.Service) *MockDomainServicesTracingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) UnitState() *service45.LeadershipService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnitState")
	ret0, _ := ret[0].(*service45.LeadershipService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) UnitState() *MockDomainServicesUnitStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnitState", reflect.TypeOf((*MockDomainServices)(nil).UnitState))
	return &MockDomainServicesUnitStateCall{Call: call}
}
func (c *MockDomainServicesUnitStateCall) Return(arg0 *service45.LeadershipService) *MockDomainServicesUnitStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesUnitStateCall) Do(f func() *service45.LeadershipService) *MockDomainServicesUnitStateCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesUnitStateCall) DoAndReturn(f func() *service45.LeadershipService) *MockDomainServicesUnitStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
func (m *MockDomainServices) Upgrade() *service46.WatchableService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade")
	ret0, _ := ret[0].(*service46.WatchableService)
	return ret0
}
func (mr *MockDomainServicesMockRecorder) Upgrade() *MockDomainServicesUpgradeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockDomainServices)(nil).Upgrade))
	return &MockDomainServicesUpgradeCall{Call: call}
}
func (c *MockDomainServicesUpgradeCall) Return(arg0 *service46.WatchableService) *MockDomainServicesUpgradeCall {
	c.Call = c.Call.Return(arg0)
	return c
}
func (c *MockDomainServicesUpgradeCall) Do(f func() *service46.WatchableService) *MockDomainServicesUpgradeCall {
	c.Call = c.Call.Do(f)
	return c
}
func (c *MockDomainServicesUpgradeCall) DoAndReturn(f func() *service46.WatchableService) *MockDomainServicesUpgradeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ServicesForModel mocks base method.

// ServicesForModel indicates an expected call of ServicesForModel.

// MockDomainServicesGetterServicesForModelCall wrap *gomock.Call
type MockDomainServicesGetterServicesForModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// MockDomainServices is a mock of DomainServices interface.
type MockDomainServices struct {
	ctrl     *gomock.Controller
	recorder *MockDomainServicesMockRecorder
}

// MockDomainServicesMockRecorder is the mock recorder for MockDomainServices.
type MockDomainServicesMockRecorder struct {
	mock *MockDomainServices
}

// NewMockDomainServices creates a new mock instance.

// EXPECT returns an object that allows the caller to indicate expected use.

// Access mocks base method.

// Access indicates an expected call of Access.

// MockDomainServicesAccessCall wrap *gomock.Call
type MockDomainServicesAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Agent mocks base method.

// Agent indicates an expected call of Agent.

// MockDomainServicesAgentCall wrap *gomock.Call
type MockDomainServicesAgentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// AgentBinary mocks base method.

// AgentBinary indicates an expected call of AgentBinary.

// MockDomainServicesAgentBinaryCall wrap *gomock.Call
type MockDomainServicesAgentBinaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// AgentBinaryStore mocks base method.

// AgentBinaryStore indicates an expected call of AgentBinaryStore.

// MockDomainServicesAgentBinaryStoreCall wrap *gomock.Call
type MockDomainServicesAgentBinaryStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// AgentPassword mocks base method.

// AgentPassword indicates an expected call of AgentPassword.

// MockDomainServicesAgentPasswordCall wrap *gomock.Call
type MockDomainServicesAgentPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// AgentProvisioner mocks base method.

// AgentProvisioner indicates an expected call of AgentProvisioner.

// MockDomainServicesAgentProvisionerCall wrap *gomock.Call
type MockDomainServicesAgentProvisionerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Annotation mocks base method.

// Annotation indicates an expected call of Annotation.

// MockDomainServicesAnnotationCall wrap *gomock.Call
type MockDomainServicesAnnotationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Application mocks base method.

// Application indicates an expected call of Application.

// MockDomainServicesApplicationCall wrap *gomock.Call
type MockDomainServicesApplicationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// AutocertCache mocks base method.

// AutocertCache indicates an expected call of AutocertCache.

// MockDomainServicesAutocertCacheCall wrap *gomock.Call
type MockDomainServicesAutocertCacheCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// BlockCommand mocks base method.

// BlockCommand indicates an expected call of BlockCommand.

// MockDomainServicesBlockCommandCall wrap *gomock.Call
type MockDomainServicesBlockCommandCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// BlockDevice mocks base method.

// BlockDevice indicates an expected call of BlockDevice.

// MockDomainServicesBlockDeviceCall wrap *gomock.Call
type MockDomainServicesBlockDeviceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ChangeStream mocks base method.

// ChangeStream indicates an expected call of ChangeStream.

// MockDomainServicesChangeStreamCall wrap *gomock.Call
type MockDomainServicesChangeStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Cloud mocks base method.

// Cloud indicates an expected call of Cloud.

// MockDomainServicesCloudCall wrap *gomock.Call
type MockDomainServicesCloudCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// CloudImageMetadata mocks base method.

// CloudImageMetadata indicates an expected call of CloudImageMetadata.

// MockDomainServicesCloudImageMetadataCall wrap *gomock.Call
type MockDomainServicesCloudImageMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Config mocks base method.

// Config indicates an expected call of Config.

// MockDomainServicesConfigCall wrap *gomock.Call
type MockDomainServicesConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Controller mocks base method.

// Controller indicates an expected call of Controller.

// MockDomainServicesControllerCall wrap *gomock.Call
type MockDomainServicesControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ControllerAgentBinaryStore mocks base method.

// ControllerAgentBinaryStore indicates an expected call of ControllerAgentBinaryStore.

// MockDomainServicesControllerAgentBinaryStoreCall wrap *gomock.Call
type MockDomainServicesControllerAgentBinaryStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ControllerChangeStream mocks base method.

// ControllerChangeStream indicates an expected call of ControllerChangeStream.

// MockDomainServicesControllerChangeStreamCall wrap *gomock.Call
type MockDomainServicesControllerChangeStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ControllerConfig mocks base method.

// ControllerConfig indicates an expected call of ControllerConfig.

// MockDomainServicesControllerConfigCall wrap *gomock.Call
type MockDomainServicesControllerConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ControllerNode mocks base method.

// ControllerNode indicates an expected call of ControllerNode.

// MockDomainServicesControllerNodeCall wrap *gomock.Call
type MockDomainServicesControllerNodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ControllerUpgrader mocks base method.

// ControllerUpgrader indicates an expected call of ControllerUpgrader.

// MockDomainServicesControllerUpgraderCall wrap *gomock.Call
type MockDomainServicesControllerUpgraderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Credential mocks base method.

// Credential indicates an expected call of Credential.

// MockDomainServicesCredentialCall wrap *gomock.Call
type MockDomainServicesCredentialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// CrossModelRelation mocks base method.

// CrossModelRelation indicates an expected call of CrossModelRelation.

// MockDomainServicesCrossModelRelationCall wrap *gomock.Call
type MockDomainServicesCrossModelRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Export mocks base method.

// Export indicates an expected call of Export.

// MockDomainServicesExportCall wrap *gomock.Call
type MockDomainServicesExportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ExternalController mocks base method.

// ExternalController indicates an expected call of ExternalController.

// MockDomainServicesExternalControllerCall wrap *gomock.Call
type MockDomainServicesExternalControllerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Flag mocks base method.

// Flag indicates an expected call of Flag.

// MockDomainServicesFlagCall wrap *gomock.Call
type MockDomainServicesFlagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// KeyManager mocks base method.

// KeyManager indicates an expected call of KeyManager.

// MockDomainServicesKeyManagerCall wrap *gomock.Call
type MockDomainServicesKeyManagerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// KeyManagerWithImporter mocks base method.

// KeyManagerWithImporter indicates an expected call of KeyManagerWithImporter.

// MockDomainServicesKeyManagerWithImporterCall wrap *gomock.Call
type MockDomainServicesKeyManagerWithImporterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// KeyUpdater mocks base method.

// KeyUpdater indicates an expected call of KeyUpdater.

// MockDomainServicesKeyUpdaterCall wrap *gomock.Call
type MockDomainServicesKeyUpdaterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Logging mocks base method.

// Logging indicates an expected call of Logging.

// MockDomainServicesLoggingCall wrap *gomock.Call
type MockDomainServicesLoggingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Macaroon mocks base method.

// Macaroon indicates an expected call of Macaroon.

// MockDomainServicesMacaroonCall wrap *gomock.Call
type MockDomainServicesMacaroonCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Machine mocks base method.

// Machine indicates an expected call of Machine.

// MockDomainServicesMachineCall wrap *gomock.Call
type MockDomainServicesMachineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Model mocks base method.

// Model indicates an expected call of Model.

// MockDomainServicesModelCall wrap *gomock.Call
type MockDomainServicesModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ModelDefaults mocks base method.

// ModelDefaults indicates an expected call of ModelDefaults.

// MockDomainServicesModelDefaultsCall wrap *gomock.Call
type MockDomainServicesModelDefaultsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ModelInfo mocks base method.

// ModelInfo indicates an expected call of ModelInfo.

// MockDomainServicesModelInfoCall wrap *gomock.Call
type MockDomainServicesModelInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ModelMigration mocks base method.

// ModelMigration indicates an expected call of ModelMigration.

// MockDomainServicesModelMigrationCall wrap *gomock.Call
type MockDomainServicesModelMigrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ModelProvider mocks base method.

// ModelProvider indicates an expected call of ModelProvider.

// MockDomainServicesModelProviderCall wrap *gomock.Call
type MockDomainServicesModelProviderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// ModelSecretBackend mocks base method.

// ModelSecretBackend indicates an expected call of ModelSecretBackend.

// MockDomainServicesModelSecretBackendCall wrap *gomock.Call
type MockDomainServicesModelSecretBackendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Network mocks base method.

// Network indicates an expected call of Network.

// MockDomainServicesNetworkCall wrap *gomock.Call
type MockDomainServicesNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Operation mocks base method.

// Operation indicates an expected call of Operation.

// MockDomainServicesOperationCall wrap *gomock.Call
type MockDomainServicesOperationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Port mocks base method.

// Port indicates an expected call of Port.

// MockDomainServicesPortCall wrap *gomock.Call
type MockDomainServicesPortCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Provisioning mocks base method.

// Provisioning indicates an expected call of Provisioning.

// MockDomainServicesProvisioningCall wrap *gomock.Call
type MockDomainServicesProvisioningCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Proxy mocks base method.

// Proxy indicates an expected call of Proxy.

// MockDomainServicesProxyCall wrap *gomock.Call
type MockDomainServicesProxyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Relation mocks base method.

// Relation indicates an expected call of Relation.

// MockDomainServicesRelationCall wrap *gomock.Call
type MockDomainServicesRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Removal mocks base method.

// Removal indicates an expected call of Removal.

// MockDomainServicesRemovalCall wrap *gomock.Call
type MockDomainServicesRemovalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Resolve mocks base method.

// Resolve indicates an expected call of Resolve.

// MockDomainServicesResolveCall wrap *gomock.Call
type MockDomainServicesResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Resource mocks base method.

// Resource indicates an expected call of Resource.

// MockDomainServicesResourceCall wrap *gomock.Call
type MockDomainServicesResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Secret mocks base method.

// Secret indicates an expected call of Secret.

// MockDomainServicesSecretCall wrap *gomock.Call
type MockDomainServicesSecretCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// SecretBackend mocks base method.

// SecretBackend indicates an expected call of SecretBackend.

// MockDomainServicesSecretBackendCall wrap *gomock.Call
type MockDomainServicesSecretBackendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Status mocks base method.

// Status indicates an expected call of Status.

// MockDomainServicesStatusCall wrap *gomock.Call
type MockDomainServicesStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Storage mocks base method.

// Storage indicates an expected call of Storage.

// MockDomainServicesStorageCall wrap *gomock.Call
type MockDomainServicesStorageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// StorageProvisioning mocks base method.

// StorageProvisioning indicates an expected call of StorageProvisioning.

// MockDomainServicesStorageProvisioningCall wrap *gomock.Call
type MockDomainServicesStorageProvisioningCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Tracing mocks base method.

// Tracing indicates an expected call of Tracing.

// MockDomainServicesTracingCall wrap *gomock.Call
type MockDomainServicesTracingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// UnitState mocks base method.

// UnitState indicates an expected call of UnitState.

// MockDomainServicesUnitStateCall wrap *gomock.Call
type MockDomainServicesUnitStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn

// Upgrade mocks base method.

// Upgrade indicates an expected call of Upgrade.

// MockDomainServicesUpgradeCall wrap *gomock.Call
type MockDomainServicesUpgradeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return

// Do rewrite *gomock.Call.Do

// DoAndReturn rewrite *gomock.Call.DoAndReturn
